test compile

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -28,3 +28,21 @@ jobs:
                     exit 1
                 fi
                 exit 0
+
+    complie:
+        runs-on: ubuntu-latest
+        steps:
+
+            - name: Checkout GH repo
+              uses: actions/checkout@v4
+
+            - name: Compile repository
+              run: make
+
+            - name: Check binary presence
+              run: |
+                if [ ! -f ./swapupcase ]; then
+                    echo "::error file=swapcase, title=Binary Error:: Binary not found::$ERROR"
+                    exit 1
+                fi
+                exit 0
